//This file is generated by LAK GenerateUtils...
package  net.is_bg.ltf.businessmodels.softuni.userdata;


import java.sql.*; 
import net.is_bg.ltf.db.common.UpdateSqlStatement;
import java.util.Date; 

import net.is_bg.ltf.util.DateUtil;



public class UserdataUpdate extends UpdateSqlStatement{


	private Userdata model;


	public UserdataUpdate(Userdata model ){
		this.model = model ;
	}


	@Override 
	protected String getSqlString() {
		 String sql = "";
		 sql += 		" update user_data set  "+
 		",username = ? "+
		",email = ? "+
		",created_date = ? "+
		",password = ? "+
		",image = ? "+
		" where user_id = ?  ";		return  sql ;
	}


	@Override 
	protected void setParameters(PreparedStatement prStmt) throws SQLException  {
		bindVarData.setString (model.getUsername());
		bindVarData.setString (model.getEmail());
		bindVarData.setDate (DateUtil.toSQLDate(model.getCreateddate()));
		bindVarData.setString (model.getPassword());
		bindVarData.setString (model.getImage());
		bindVarData.setLong (model.getId());
		bindVarData.setParameters(prStmt);
	}
}
