//This file is generated by LAK GenerateUtils...
package  net.is_bg.ltf.businessmodels.softuni.userdata;


import java.sql.*; 
import net.is_bg.ltf.db.common.UpdateSqlStatement;
import net.is_bg.ltf.jwt.Sha512;

public class UserdataInsert extends UpdateSqlStatement{

	private Userdata model;

	public UserdataInsert(Userdata model ){
		this.model = model ;
	}


	@Override 
	protected String getSqlString() {
		 String sql = "";
		 sql += " insert into user_data (user_id,username,email,created_date,password,image) values (";

			if (model.getId() >  0) sql += " ?  ";
			else  sql +=  " snextval('s_user_data')";

		 sql+= ",?,?,current_date,?,?) ";
		return  sql;
	}


	@Override 
	protected void setParameters(PreparedStatement prStmt) throws SQLException  {
		if (model.getId() >  0)		bindVarData.setLong (model.getId());
		bindVarData.setString (model.getUsername());
		bindVarData.setString (model.getEmail());
		bindVarData.setString (new Sha512().digest(model.getPassword()));
		bindVarData.setString (model.getImage());
		bindVarData.setParameters(prStmt);
	}
}
