//This file is generated by LAK GenerateUtils...
package  net.is_bg.ltf.businessmodels.softuni.userdata;
import java.sql.*; 
import java.math.BigDecimal; 
import net.is_bg.ltf.AbstractModel; 
import java.util.Date; 
/**
export interface  IUserdata{
	id:number,
	username:string,
	email:string,
	createddate:Date ,
	password:string,
	image:string
}
*/
public class Userdata extends AbstractModel{


//member variables...
	private String  username;
	private String  email;
	private Date  createddate;
	private String  password;
	private String  image;
    

//getters & setters
	public String getUsername(){
		return username;
	}
	public void setUsername(String username){
		this.username = username;
	}
	public String getEmail(){
		return email;
	}
	public void setEmail(String email){
		this.email = email;
	}
	public Date getCreateddate(){
		return createddate;
	}
	public void setCreateddate(Date createddate){
		this.createddate = createddate;
	}
	public String getPassword(){
		return password;
	}
	public void setPassword(String password){
		this.password = password;
	}
	public String getImage(){
		return image;
	}
	public void setImage(String image){
		this.image = image;
	}
	
	public UserDataFrontEnd touserDataFronEnd() {
		UserDataFrontEnd ufe =  new UserDataFrontEnd();
		ufe.setId(getId());
		ufe.setImage(image);
		ufe.setEmail(email);
		ufe.setUsername(username);
		return ufe;
	}
	 
}