//This file is generated by LAK GenerateUtils...
package  net.is_bg.ltf.businessmodels.softuni.users;


import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.SQLException;

import net.is_bg.ltf.db.common.UpdateSqlStatement;
import net.is_bg.ltf.jwt.Sha512;
import net.is_bg.ltf.util.DateUtil;



public class UsersInsert extends UpdateSqlStatement{


	private Users model;


	public UsersInsert(Users model ){
		this.model = model ;
	}


	@Override 
	protected String getSqlString() {
		 String sql = "";
		 sql += " insert into users (user_id,username,fullname,email,end_date,created_date,password,image,skin) values (";

			if (model.getId() >  0) sql += " ?  ";
			else  sql +=  " snextval('s_users')";

		 sql+= ",?,?,?,?,current_date,?,?,?) ";
		return  sql ;
	}


	@Override 
	protected void setParameters(PreparedStatement prStmt) throws SQLException  {
		if (model.getId() >  0)		bindVarData.setLong (model.getId());
		bindVarData.setString (model.getUsername());
		bindVarData.setString (model.getFullname());
		bindVarData.setString (model.getEmail());
		bindVarData.setDate ( DateUtil.toSQLDate(model.getEnddate()));
		bindVarData.setString (new Sha512().digest(model.getPassword()));
		bindVarData.setString (model.getImage());
		bindVarData.setString (model.getSkin());
		bindVarData.setParameters(prStmt);
	}
}
