//This file is generated by LAK GenerateUtils...
package  net.is_bg.ltf.businessmodels.softuni.users;


import java.sql.*; 
import net.is_bg.ltf.db.common.UpdateSqlStatement;
import java.util.Date; 

import net.is_bg.ltf.util.DateUtil;



public class UsersDelete extends UpdateSqlStatement{


	private Users model;


	public UsersDelete(Users model ){
		this.model = model ;
	}

	public UsersDelete( long id ){
		this.model =  new Users();
		this.model.setId(id);
	}


	@Override 
	protected String getSqlString() {
		 String sql = "";
		 sql += " delete from users where user_id = ?  ";		return  sql ;
	}


	@Override 
	protected void setParameters(PreparedStatement prStmt) throws SQLException  {
		bindVarData.setLong (model.getId());
		bindVarData.setParameters(prStmt);
	}
}
