//This file is generated by LAK GenerateUtils...
package  net.is_bg.ltf.businessmodels.softuni.users;
import java.sql.*; 
import java.math.BigDecimal; 
import net.is_bg.ltf.AbstractModel; 
import java.util.Date; 
/**
export interface  IUsers{
	id:number,
	username:string,
	fullname:string,
	email:string,
	enddate:Date ,
	createddate:Date ,
	password:string,
	image:string,
	skin:string
}
*/
public class Users extends AbstractModel{


//member variables...
	private String  username;
	private String  fullname;
	private String  email;
	private Date    enddate;
	private Date    createddate;
	private String  password;
	private String  image;
	private String  skin;


//getters & setters
	public String getUsername(){
		return username;
	}
	public void setUsername(String username){
		this.username = username;
	}
	public String getFullname(){
		return fullname;
	}
	public void setFullname(String fullname){
		this.fullname = fullname;
	}
	public String getEmail(){
		return email;
	}
	public void setEmail(String email){
		this.email = email;
	}
	public Date getEnddate(){
		return enddate;
	}
	public void setEnddate(Date enddate){
		this.enddate = enddate;
	}
	public Date getCreateddate(){
		return createddate;
	}
	public void setCreateddate(Date createddate){
		this.createddate = createddate;
	}
	public String getPassword(){
		return password;
	}
	public void setPassword(String password){
		this.password = password;
	}
	public String getImage(){
		return image;
	}
	public void setImage(String image){
		this.image = image;
	}
	public String getSkin(){
		return skin;
	}
	public void setSkin(String skin){
		this.skin = skin;
	}
}