//This file is generated by LAK GenerateUtils...
package  net.is_bg.ltf.businessmodels.softuni.userorder;


import java.sql.*; 
import net.is_bg.ltf.db.common.UpdateSqlStatement;
import java.util.Date; 

import net.is_bg.ltf.util.DateUtil;



public class UserorderDelete extends UpdateSqlStatement{


	private Userorder model;


	public UserorderDelete(Userorder model ){
		this.model = model ;
	}

	public UserorderDelete( long id ){
		this.model =  new Userorder();
		this.model.setId(id);
	}


	@Override 
	protected String getSqlString() {
		 String sql = "";
		 sql += " delete from user_order where order_id = ?  ";		return  sql ;
	}


	@Override 
	protected void setParameters(PreparedStatement prStmt) throws SQLException  {
		bindVarData.setLong (model.getId());
		bindVarData.setParameters(prStmt);
	}
}
