//This file is generated by LAK GenerateUtils...
package  net.is_bg.ltf.businessmodels.softuni.userorder;
import java.sql.*; 
import java.math.BigDecimal; 
import net.is_bg.ltf.AbstractModel; 
import java.util.Date; 
/**
export interface  IUserorder{
	id:number,
	userid:number,
	serviceid:number,
	ordertime:Date 
}
*/
public class Userorder extends AbstractModel{


//member variables...
	private long  userid;
	private long  serviceid;
	private Date  ordertime;


//getters & setters
	public long getUserid(){
		return userid;
	}
	public void setUserid(long userid){
		this.userid = userid;
	}
	public long getServiceid(){
		return serviceid;
	}
	public void setServiceid(long serviceid){
		this.serviceid = serviceid;
	}
	public Date getOrdertime(){
		return ordertime;
	}
	public void setOrdertime(Date ordertime){
		this.ordertime = ordertime;
	}
}