//This file is generated by LAK GenerateUtils...
package  net.is_bg.ltf.businessmodels.softuni.userorder;


import java.sql.*; 
import net.is_bg.ltf.db.common.UpdateSqlStatement;
import java.util.Date; 

import net.is_bg.ltf.util.DateUtil;



public class UserorderInsert extends UpdateSqlStatement{


	private Userorder model;


	public UserorderInsert(Userorder model ){
		this.model = model ;
	}


	@Override 
	protected String getSqlString() {
		 String sql = "";
		 sql += " insert into user_order (order_id,user_id,service_id,order_time) values (";

			if (model.getId() >  0) sql += " ?  ";
			else  sql +=  " snextval('s_user_order')";

		 sql+= ",?,?,?) ";
		return  sql ;
	}


	@Override 
	protected void setParameters(PreparedStatement prStmt) throws SQLException  {
		if (model.getId() >  0)		bindVarData.setLong (model.getId());
		bindVarData.setLong (model.getUserid());
		bindVarData.setLong (model.getServiceid());
		bindVarData.setDate (DateUtil.toSQLDate(model.getOrdertime()));
		bindVarData.setParameters(prStmt);
	}
}
