//This file is generated by LAK GenerateUtils...
package  net.is_bg.ltf.businessmodels.softuni.userorder;


import java.sql.*; 
import net.is_bg.ltf.db.common.UpdateSqlStatement;
import java.util.Date; 

import net.is_bg.ltf.util.DateUtil;



public class UserorderUpdate extends UpdateSqlStatement{


	private Userorder model;


	public UserorderUpdate(Userorder model ){
		this.model = model ;
	}


	@Override 
	protected String getSqlString() {
		 String sql = "";
		 sql += 		" update user_order set  "+
 		",user_id = ? "+
		",service_id = ? "+
		",order_time = ? "+
		" where order_id = ?  ";		return  sql ;
	}


	@Override 
	protected void setParameters(PreparedStatement prStmt) throws SQLException  {
		bindVarData.setLong (model.getUserid());
		bindVarData.setLong (model.getServiceid());
		bindVarData.setDate (DateUtil.toSQLDate(model.getOrdertime()));
		bindVarData.setLong (model.getId());
		bindVarData.setParameters(prStmt);
	}
}
