//This file is generated by LAK GenerateUtils...
package  net.is_bg.ltf.businessmodels.softuni.servicegroup;


import java.sql.*; 
import net.is_bg.ltf.db.common.UpdateSqlStatement;
import java.util.Date; 

import net.is_bg.ltf.util.DateUtil;



public class ServicegroupDelete extends UpdateSqlStatement{


	private Servicegroup model;


	public ServicegroupDelete(Servicegroup model ){
		this.model = model ;
	}

	public ServicegroupDelete( long id ){
		this.model =  new Servicegroup();
		this.model.setId(id);
	}


	@Override 
	protected String getSqlString() {
		 String sql = "";
		 sql += " delete from service_group where service_group_id = ?  ";		return  sql ;
	}


	@Override 
	protected void setParameters(PreparedStatement prStmt) throws SQLException  {
		bindVarData.setLong (model.getId());
		bindVarData.setParameters(prStmt);
	}
}
