//This file is generated by LAK GenerateUtils...
package  net.is_bg.ltf.businessmodels.softuni.servicegroup;


import java.sql.*; 
import net.is_bg.ltf.db.common.UpdateSqlStatement;
import java.util.Date; 

import net.is_bg.ltf.util.DateUtil;



public class ServicegroupInsert extends UpdateSqlStatement{


	private Servicegroup model;


	public ServicegroupInsert(Servicegroup model ){
		this.model = model ;
	}


	@Override 
	protected String getSqlString() {
		 String sql = "";
		 sql += " insert into service_group (service_group_id,service_group_name) values (";

			if (model.getId() >  0) sql += " ?  ";
			else  sql +=  " snextval('s_service_group')";

		 sql+= ",?) ";
		return  sql ;
	}


	@Override 
	protected void setParameters(PreparedStatement prStmt) throws SQLException  {
		if (model.getId() >  0)		bindVarData.setLong (model.getId());
		bindVarData.setString (model.getServicegroupname());
		bindVarData.setParameters(prStmt);
	}
}
