//This file is generated by LAK GenerateUtils...
package  net.is_bg.ltf.businessmodels.softuni.service;
import java.sql.*; 
import java.math.BigDecimal; 
import net.is_bg.ltf.AbstractModel; 
import java.util.Date; 
/**
export interface  IService{
	id:number,
	name:string,
	servicegroupid:number,
	price:number
}
*/
public class Service extends AbstractModel{


//member variables...
	private String  name;
	private long  servicegroupid;
	private BigDecimal  price;


//getters & setters
	public String getName(){
		return name;
	}
	public void setName(String name){
		this.name = name;
	}
	public long getServicegroupid(){
		return servicegroupid;
	}
	public void setServicegroupid(long servicegroupid){
		this.servicegroupid = servicegroupid;
	}
	public BigDecimal getPrice(){
		return price;
	}
	public void setPrice(BigDecimal price){
		this.price = price;
	}
}