//This file is generated by LAK GenerateUtils...
package  net.is_bg.ltf.businessmodels.softuni.service;


import java.sql.*; 
import net.is_bg.ltf.db.common.UpdateSqlStatement;
import java.util.Date; 

import net.is_bg.ltf.util.DateUtil;



public class ServiceDelete extends UpdateSqlStatement{


	private Service model;


	public ServiceDelete(Service model ){
		this.model = model ;
	}

	public ServiceDelete( long id ){
		this.model =  new Service();
		this.model.setId(id);
	}


	@Override 
	protected String getSqlString() {
		 String sql = "";
		 sql += " delete from service where service_id = ?  ";		return  sql ;
	}


	@Override 
	protected void setParameters(PreparedStatement prStmt) throws SQLException  {
		bindVarData.setLong (model.getId());
		bindVarData.setParameters(prStmt);
	}
}
