//This file is generated by LAK GenerateUtils...
package  net.is_bg.ltf.businessmodels.softuni.stuff;


import java.sql.*; 
import net.is_bg.ltf.db.common.UpdateSqlStatement;
import java.util.Date; 

import net.is_bg.ltf.util.DateUtil;



public class StuffDelete extends UpdateSqlStatement{


	private Stuff model;


	public StuffDelete(Stuff model ){
		this.model = model ;
	}

	public StuffDelete( long id ){
		this.model =  new Stuff();
		this.model.setId(id);
	}


	@Override 
	protected String getSqlString() {
		 String sql = "";
		 sql += " delete from stuff where stuff_id = ?  ";		return  sql ;
	}


	@Override 
	protected void setParameters(PreparedStatement prStmt) throws SQLException  {
		bindVarData.setLong (model.getId());
		bindVarData.setParameters(prStmt);
	}
}
