//This file is generated by LAK GenerateUtils...
package  net.is_bg.ltf.businessmodels.softuni.stuff;
import java.sql.*; 
import java.math.BigDecimal; 
import net.is_bg.ltf.AbstractModel; 
import java.util.Date; 
/**
export interface  IStuff{
	id:number,
	name:string,
	phone:string,
	image:string,
	description:string,
	userid:number,
	workhours:string,
	likes:number,
	dislikes:number
}
*/
public class Stuff extends AbstractModel{


//member variables...
	private String  name;
	private String  phone;
	private String  image;
	private String  description;
	private long  userid;
	private String  workhours;
	private long  likes;
	private long  dislikes;


//getters & setters
	public String getName(){
		return name;
	}
	public void setName(String name){
		this.name = name;
	}
	public String getPhone(){
		return phone;
	}
	public void setPhone(String phone){
		this.phone = phone;
	}
	public String getImage(){
		return image;
	}
	public void setImage(String image){
		this.image = image;
	}
	public String getDescription(){
		return description;
	}
	public void setDescription(String description){
		this.description = description;
	}
	public long getUserid(){
		return userid;
	}
	public void setUserid(long userid){
		this.userid = userid;
	}
	public String getWorkhours(){
		return workhours;
	}
	public void setWorkhours(String workhours){
		this.workhours = workhours;
	}
	public long getLikes(){
		return likes;
	}
	public void setLikes(long likes){
		this.likes = likes;
	}
	public long getDislikes(){
		return dislikes;
	}
	public void setDislikes(long dislikes){
		this.dislikes = dislikes;
	}
}