//This file is generated by LAK GenerateUtils...
package  net.is_bg.ltf.businessmodels.softuni.stuff;


import java.sql.*; 
import net.is_bg.ltf.db.common.UpdateSqlStatement;
import java.util.Date; 

import net.is_bg.ltf.util.DateUtil;



public class StuffInsert extends UpdateSqlStatement{


	private Stuff model;


	public StuffInsert(Stuff model ){
		this.model = model ;
	}


	@Override 
	protected String getSqlString() {
		 String sql = "";
		 sql += " insert into stuff (stuff_id,name,phone,image,description,user_id,work_hours,likes,dislikes) values (";

			if (model.getId() >  0) sql += " ?  ";
			else  sql +=  " snextval('s_stuff')";

		 sql+= ",?,?,?,?,?,?,?,?) ";
		return  sql ;
	}


	@Override 
	protected void setParameters(PreparedStatement prStmt) throws SQLException  {
		if (model.getId() >  0)		bindVarData.setLong (model.getId());
		bindVarData.setString (model.getName());
		bindVarData.setString (model.getPhone());
		bindVarData.setString (model.getImage());
		bindVarData.setString (model.getDescription());
		bindVarData.setLong (model.getUserid());
		bindVarData.setString (model.getWorkhours());
		bindVarData.setLong (model.getLikes());
		bindVarData.setLong (model.getDislikes());
		bindVarData.setParameters(prStmt);
	}
}
