//This file is generated by LAK GenerateUtils...
package  net.is_bg.ltf.businessmodels.softuni.promotion;


import java.sql.*; 
import net.is_bg.ltf.db.common.UpdateSqlStatement;
import java.util.Date; 

import net.is_bg.ltf.util.DateUtil;



public class PromotionDelete extends UpdateSqlStatement{


	private Promotion model;


	public PromotionDelete(Promotion model ){
		this.model = model ;
	}

	public PromotionDelete( long id ){
		this.model =  new Promotion();
		this.model.setId(id);
	}


	@Override 
	protected String getSqlString() {
		 String sql = "";
		 sql += " delete from promotion where promotion_id = ?  ";		return  sql ;
	}


	@Override 
	protected void setParameters(PreparedStatement prStmt) throws SQLException  {
		bindVarData.setLong (model.getId());
		bindVarData.setParameters(prStmt);
	}
}
