//This file is generated by LAK GenerateUtils...
package  net.is_bg.ltf.businessmodels.softuni.promotion;


import java.sql.*; 
import net.is_bg.ltf.db.common.UpdateSqlStatement;
import java.util.Date; 

import net.is_bg.ltf.util.DateUtil;



public class PromotionInsert extends UpdateSqlStatement{


	private Promotion model;


	public PromotionInsert(Promotion model ){
		this.model = model ;
	}


	@Override 
	protected String getSqlString() {
		 String sql = "";
		 sql += " insert into promotion (promotion_id,expire_date,service_id,discount) values (";

			if (model.getId() >  0) sql += " ?  ";
			else  sql +=  " snextval('s_promotion')";

		 sql+= ",?,?,?) ";
		return  sql ;
	}


	@Override 
	protected void setParameters(PreparedStatement prStmt) throws SQLException  {
		if (model.getId() >  0)		bindVarData.setLong (model.getId());
		bindVarData.setDate (DateUtil.toSQLDate(model.getExpiredate()));
		bindVarData.setLong (model.getProcedure().getId());
		bindVarData.setLong (model.getDicscount());
		bindVarData.setParameters(prStmt);
	}
}
