//This file is generated by LAK GenerateUtils...
package  net.is_bg.ltf.businessmodels.softuni.payment;


import java.sql.*; 
import net.is_bg.ltf.db.common.UpdateSqlStatement;
import java.util.Date; 

import net.is_bg.ltf.util.DateUtil;



public class PaymentDelete extends UpdateSqlStatement{


	private Payment model;


	public PaymentDelete(Payment model ){
		this.model = model ;
	}

	public PaymentDelete( long id ){
		this.model =  new Payment();
		this.model.setId(id);
	}


	@Override 
	protected String getSqlString() {
		 String sql = "";
		 sql += " delete from payment where payment_id = ?  ";		return  sql ;
	}


	@Override 
	protected void setParameters(PreparedStatement prStmt) throws SQLException  {
		bindVarData.setLong (model.getId());
		bindVarData.setParameters(prStmt);
	}
}
