//This file is generated by LAK GenerateUtils...
package  net.is_bg.ltf.businessmodels.softuni.payment;


import java.sql.*; 
import net.is_bg.ltf.db.common.UpdateSqlStatement;
import java.util.Date; 

import net.is_bg.ltf.util.DateUtil;



public class PaymentUpdate extends UpdateSqlStatement{


	private Payment model;


	public PaymentUpdate(Payment model ){
		this.model = model ;
	}


	@Override 
	protected String getSqlString() {
		 String sql = "";
		 sql += 		" update payment set  "+
 		",reservation_id = ? "+
		",paytime = ? "+
		",sum = ? "+
		",pay_card_id = ? "+
		" where payment_id = ?  ";		return  sql ;
	}


	@Override 
	protected void setParameters(PreparedStatement prStmt) throws SQLException  {
		bindVarData.setLong (model.getReservationid());
		bindVarData.setDate (DateUtil.toSQLDate(model.getPaytime()));
		bindVarData.setBigDecimal (model.getSum());
		bindVarData.setLong (model.getPaycardid());
		bindVarData.setLong (model.getId());
		bindVarData.setParameters(prStmt);
	}
}
