//This file is generated by LAK GenerateUtils...
package  net.is_bg.ltf.businessmodels.softuni.payment;
import java.sql.*; 
import java.math.BigDecimal; 
import net.is_bg.ltf.AbstractModel; 
import java.util.Date; 
/**
export interface  IPayment{
	id:number,
	reservationid:number,
	paytime:Date ,
	sum:number,
	paycardid:number
}
*/
public class Payment extends AbstractModel{


//member variables...
	private long  reservationid;
	private Date  paytime;
	private BigDecimal  sum;
	private long  paycardid;


//getters & setters
	public long getReservationid(){
		return reservationid;
	}
	public void setReservationid(long reservationid){
		this.reservationid = reservationid;
	}
	public Date getPaytime(){
		return paytime;
	}
	public void setPaytime(Date paytime){
		this.paytime = paytime;
	}
	public BigDecimal getSum(){
		return sum;
	}
	public void setSum(BigDecimal sum){
		this.sum = sum;
	}
	public long getPaycardid(){
		return paycardid;
	}
	public void setPaycardid(long paycardid){
		this.paycardid = paycardid;
	}
}