//This file is generated by LAK GenerateUtils...
package  net.is_bg.ltf.businessmodels.softuni.payment;


import java.sql.*; 
import net.is_bg.ltf.db.common.UpdateSqlStatement;
import java.util.Date; 

import net.is_bg.ltf.util.DateUtil;



public class PaymentInsert extends UpdateSqlStatement{


	private Payment model;


	public PaymentInsert(Payment model ){
		this.model = model ;
	}


	@Override 
	protected String getSqlString() {
		 String sql = "";
		 sql += " insert into payment (payment_id,reservation_id,paytime,sum,pay_card_id) values (";

			if (model.getId() >  0) sql += " ?  ";
			else  sql +=  " snextval('s_payment')";

		 sql+= ",?,?,?,?) ";
		return  sql ;
	}


	@Override 
	protected void setParameters(PreparedStatement prStmt) throws SQLException  {
		if (model.getId() >  0)		bindVarData.setLong (model.getId());
		bindVarData.setLong (model.getReservationid());
		bindVarData.setDate (DateUtil.toSQLDate(model.getPaytime()));
		bindVarData.setBigDecimal (model.getSum());
		bindVarData.setLong (model.getPaycardid());
		bindVarData.setParameters(prStmt);
	}
}
